### ISSUE TITLE
implementation timeline

### ISSUE THREAD

**Issue by easchwar** [brookeangel/Harvest#1]
Phase 1: forgot to rename `NotesController`. Should probably have `users/new.html.erb` for signing up as well as `sessions/new.html.erb` for signing in. 
Regarding your UsersController, this depends on what you plan on doing with your users. You definitely
need a non-api users controller for the `new` and `create` controller actions. But if you plan on displaying
a lot of user model information on your app, it would make sense to **also** have a `Api::UsersController`. This would handle all of the JSON you need with its corresponding actions (i.e. `show`, `index`, `edit`). Feel free to grab me if you have more questions about this.

Phase 2: Good.

Phase 3: See phase 1 notes. 

Phase 4: I'm not wild about messages being part of the MVP. They seem kind of like they're tacked on, and it requires a lot of extra boilerplate (a lot of views, stores, etc.). Maybe instead have Harvest owners be able to post in their harvest? This would be a way easier thing to add.

Phase 5: I like notifications. Super easy with Flux!

**Comment by easchwar** [comment]
Reviews are in your MVP but not in your implementation timeline. If this is a core feature you should map it out

**Comment by brookeangel** [comment]
Ooooops, I decided halfway though planning that messages were a poor idea and that instead I'd just use reviews. Apparently I forgot to replace messages with reviews in all sorts of places. Thanks!
